[tool.poetry]
name = "Western-Friend-website"
version = "0.1.0"
description = "Website for Western Friend (westernfriend.org)"
authors = ["Brylie Christopher Oxley <brylie@amble.fi>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
wagtail = "^2.7"
arrow = "^0.15.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
