[tool.poetry]
name = "Western-Friend-website"
version = "0.1.0"
description = "Website for Western Friend (westernfriend.org)"
authors = ["Brylie Christopher Oxley <brylie@amble.fi>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
arrow = "^0.15.4"
braintree = "^3.57.1"
django-crispy-forms = "^1.8.1"
django-registration = "^3.0.1"
django-flatpickr = "^1.0.1"
dj-database-url = "^0.5.0"
psycopg2-binary = "^2.8.4"
python-dotenv = "^0.14.0"
tqdm = "^4.57.0"
django-timezone-field = "^5.0"
tzdata = "^2022.1"
wagtail-color-panel = "^1.3.1"
django-storages = "^1.13.1"
boto3 = "^1.24.46"
wagtailmedia = "^0.14.0"
wagtail = "^5.0"
django-extensions = "^3.2.1"
django-stubs = "^4.2.0"
django = "^4.2.1"
django-debug-toolbar = "^4.0.0"

[tool.poetry.group.dev.dependencies]
django-browser-reload = "^1.8.0"
pre-commit = "^3.3.1"
pandas = "^2.0.1"
black = "^23.3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ['py311']

[tool.django-stubs]
django_settings_module = "core.settings.base"

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.ruff]
# Same as Black.
line-length = 88

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "**/migrations"
]

# Assume Python 3.11
target-version = "py311"
